version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8000"
    environment:
      - SERVER_NAMES=${URL}
      - CHDB_HOST=${CHDB_HOST}
      - CHDB_PORT=${CHDB_PORT}
      - CHDB_NAME=${CHDB_NAME}
      - CHDB_USER=${CHDB_USER}
      - CHDB_PASSWORD=${CHDB_PASSWORD}
      - REDDISHOST=redis
      - REDDISPORT=6379
      - REDDISPASS=
      - RRGREDISHOST=redis
      - RRGREDISPORT=6379
      - RRGREDISPASS=
      - REDDIS_SSL=False
      - REDDIS_CERT_REQS=none
      - JWT=${JWT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    restart: unless-stopped

  celery-worker:
    build:
      context: .
    command: celery -A src.celery_app worker --loglevel=INFO
    environment:
      - CELERY_REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis
      - app
    restart: unless-stopped

  celery-beat:
    build:
      context: .
    command: celery -A src.celery_app beat --loglevel=INFO
    environment:
      - CELERY_REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  redis-data: